services:
  redis:
    restart: always
    image: redis:7.0
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]


networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: