name: Run CI Tests and Push Latest (Developer Build) Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  checks: write
  contents: read
  packages: write
  pull-requests: read
  statuses: read

jobs:
  run_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Configure Tests
        run: chmod +x run_tests.sh
      - name: Run Jest Tests
        run: /bin/bash -c "./run_tests.sh"
  
  build_dev_images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Push docker image to Github Container Registry
        run: > 
          IMAGE_ARG=${{ github.sha }} docker-compose -f docker-compose.yml -f docker-compose.prod.yml build && \
          docker tag ghcr.io/harsh098/samplefullstack_backend:$IMAGE_ARG  ghcr.io/harsh098/samplefullstack_backend:dev && \
          docker tag ghcr.io/harsh098/samplefullstack_frontend:$IMAGE_ARG  ghcr.io/harsh098/samplefullstack_frontend:dev && \
          docker image push -a hcr.io/harsh098/samplefullstack_frontend && \
          docker image push -a hcr.io/harsh098/samplefullstack_backend
  

  
  
  
