name: Run CI Tests and Push Latest (Developer Build) Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  checks: write
  contents: read
  packages: write
  pull-requests: read
  statuses: read

jobs:
  run_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Configure Tests
        run: chmod +x run_tests.sh
      - name: Run CI Tests
        run: /bin/bash -c "./run_tests"
  

  
  
  
